-- Accounts the user owns. Accounts are created and renamed but never deleted.
create table account (
    id             bigint generated by default as identity primary key,
    name           varchar(255) not null,
    currency       varchar(3)      not null,
    kind           varchar(32),
    account_number varchar(255),
    sort_order     int          not null default 0,
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now()
);

-- Flat list of spending groups. Deleting a category leaves transactions uncategorized.
create table category (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    color      varchar(32),
    sort_order int          not null default 0,
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now()
);

-- One imported statement file, attributed to exactly one account.
create table bank_statement (
    id           bigint generated by default as identity primary key,
    account_id   bigint      not null references account (id),
    bank         varchar(64) not null,
    period_start date,
    period_end   date,
    file_name    varchar(255),
    file_hash    varchar(64) not null unique,
    imported_at  timestamptz not null default now()
);

-- A normalized transaction. Amount is signed: expense negative, income positive.
create table transaction (
    id                bigint generated by default as identity primary key,
    statement_id      bigint           not null references bank_statement (id) on delete cascade,
    account_id        bigint           not null references account (id),
    transaction_date  date             not null,
    amount            numeric(19, 4)   not null,
    currency          varchar(3)          not null,
    nature            varchar(16)      not null default 'EXPENSE'
                      check (nature in ('INCOME', 'EXPENSE', 'TRANSFER')),
    description       text,
    merchant          varchar(255),
    category_id       bigint           references category (id) on delete set null,
    base_amount       numeric(19, 4),
    fx_rate           numeric(20, 8),
    fx_rate_date      date,
    dedup_hash        varchar(64),
    transfer_group_id uuid,
    created_at        timestamptz      not null default now()
);

create index idx_transaction_date on transaction (transaction_date);
create index idx_transaction_account_date on transaction (account_id, transaction_date);
create index idx_transaction_account_dedup on transaction (account_id, dedup_hash);
create index idx_transaction_category on transaction (category_id);
create index idx_transaction_nature on transaction (nature);
create index idx_transaction_statement on transaction (statement_id);

-- Primary store of FX rates. Historical rates are immutable once stored.
create table fx_rate (
    id            bigint generated by default as identity primary key,
    currency      varchar(3)        not null,
    rate_date     date           not null,
    rate          numeric(20, 8) not null,
    base_currency varchar(3)        not null,
    source        varchar(32),
    created_at    timestamptz    not null default now(),
    unique (currency, rate_date, base_currency)
);

-- Default categories (seeded once; user-editable, deletable).
insert into category (id, name, color, sort_order)
values (1, 'Groceries', '#4CAF50', 10),
       (2, 'Transport', '#2196F3', 20),
       (3, 'Housing', '#9C27B0', 30),
       (4, 'Dining', '#FF9800', 40),
       (5, 'Entertainment', '#E91E63', 50);
