-- Auto-categorization rule: transactions whose counterparty matches `merchant` (compared
-- case- and spacing-insensitively) are tagged with `category_id` when imported. Deleting a
-- category removes its rules through the cascade below.
create table merchant_rule (
    id          bigint generated by default as identity primary key,
    merchant    varchar(200) not null unique,
    category_id bigint       not null references category (id) on delete cascade,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

-- V1 seeded categories with explicit ids, which does not advance the identity sequence;
-- the next insert then reuses a low id and collides with the primary key. Sync the
-- sequence to the highest seeded id so new categories get fresh ids.
select setval(pg_get_serial_sequence('category', 'id'), greatest((select max(id) from category), 1));
